[project]
name = "hello-shiny"
r_version = "4.4"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Using P3M to get pre-compiled Linux binaries (avoids needing system dev libraries).
repositories = [
    {alias = "P3M", url = "https://p3m.dev/cran/__linux__/noble/2026-03-18"},
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "shiny",
]
