package deploy

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/cynkra/blockyard/internal/detect"
	"github.com/cynkra/blockyard/internal/manifest"
)

// PrepareManifest generates a manifest based on the input case.
func PrepareManifest(dir string, det *detect.Result, reposFlag string) (*manifest.Manifest, error) {
	meta := manifest.Metadata{
		AppMode:    det.Mode,
		Entrypoint: det.Entrypoint,
	}

	switch det.InputCase {
	case detect.CaseManifest:
		// 1a: manifest.json exists — validate and use.
		m, err := manifest.Read(filepath.Join(dir, "manifest.json"))
		if err != nil {
			return nil, fmt.Errorf("invalid manifest: %w", err)
		}
		return m, nil

	case detect.CaseRenvLock:
		// 1b: renv.lock exists — convert to manifest.
		files := detect.FileChecksums(dir)
		m, err := manifest.FromRenvLock(filepath.Join(dir, "renv.lock"), meta, files)
		if err != nil {
			return nil, fmt.Errorf("convert renv.lock: %w", err)
		}
		return m, nil

	case detect.CasePinFlag:
		// 1c: --pin — shell out to R + renv, then convert.
		if err := RunRenvSnapshot(dir); err != nil {
			return nil, err
		}
		files := detect.FileChecksums(dir)
		m, err := manifest.FromRenvLock(filepath.Join(dir, "renv.lock"), meta, files)
		if err != nil {
			return nil, fmt.Errorf("convert renv.lock: %w", err)
		}
		// Clean up renv artifacts if we generated them.
		CleanRenvArtifacts(dir)
		return m, nil

	case detect.CaseDescription:
		// 2a: DESCRIPTION exists — build unpinned manifest.
		files := detect.FileChecksums(dir)
		repos := ParseReposFlag(reposFlag)
		m, err := manifest.FromDescription(filepath.Join(dir, "DESCRIPTION"), meta, files, repos)
		if err != nil {
			return nil, fmt.Errorf("convert DESCRIPTION: %w", err)
		}
		return m, nil

	case detect.CaseBareScripts:
		// 2b: bare scripts — no manifest generated, upload as-is.
		return nil, nil

	default:
		return nil, fmt.Errorf("unknown input case")
	}
}

// RunRenvSnapshot shells out to R to create an renv.lock file.
func RunRenvSnapshot(dir string) error {
	// Check that R is available.
	if _, err := exec.LookPath("Rscript"); err != nil {
		return fmt.Errorf("pinning requires R + renv; Rscript not found in PATH")
	}

	script := `options(renv.consent = TRUE)
deps <- renv::dependencies(".", quiet = TRUE, progress = FALSE)
renv::snapshot(".", packages = deps$Package, prompt = FALSE)`

	cmd := exec.Command("Rscript", "-e", script)
	cmd.Dir = dir
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("renv snapshot failed: %w", err)
	}
	return nil
}

// CleanRenvArtifacts removes renv artifacts generated by --pin.
func CleanRenvArtifacts(dir string) {
	_ = os.Remove(filepath.Join(dir, "renv.lock"))
	_ = os.RemoveAll(filepath.Join(dir, "renv"))
	_ = os.Remove(filepath.Join(dir, ".Rprofile"))
}

// ParseReposFlag parses a comma-separated repositories flag value into Repository entries.
func ParseReposFlag(flag string) []manifest.Repository {
	if flag == "" {
		return detect.DefaultRepositories()
	}
	var repos []manifest.Repository
	for i, url := range strings.Split(flag, ",") {
		url = strings.TrimSpace(url)
		if url != "" {
			name := fmt.Sprintf("repo%d", i+1)
			repos = append(repos, manifest.Repository{Name: name, URL: url})
		}
	}
	if len(repos) == 0 {
		return detect.DefaultRepositories()
	}
	return repos
}

// CreateArchive creates a tar.gz archive of the directory contents.
func CreateArchive(dir string) (*os.File, error) {
	tmp, err := os.CreateTemp("", "by-bundle-*.tar.gz")
	if err != nil {
		return nil, err
	}

	gw := gzip.NewWriter(tmp)
	tw := tar.NewWriter(gw)

	err = filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// Skip hidden files/directories.
		if d.Name() != "." && strings.HasPrefix(d.Name(), ".") {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}

		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}

		info, err := d.Info()
		if err != nil {
			return err
		}

		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = rel

		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}
		if !d.IsDir() {
			f, err := os.Open(path) //nolint:gosec // G122: walks local deploy dir, no symlink risk
			if err != nil {
				return err
			}
			defer f.Close()
			if _, err := io.Copy(tw, f); err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return nil, err
	}

	if err := tw.Close(); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return nil, err
	}
	if err := gw.Close(); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return nil, err
	}

	// Seek to beginning for reading.
	if _, err := tmp.Seek(0, 0); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return nil, err
	}
	return tmp, nil
}
