name: Publish

on:
  push:
    branches: [main]

permissions:
  packages: write

env:
  IMAGE: ghcr.io/cynkra/blockyard

jobs:
  server-image:
    uses: ./.github/workflows/server-image.yml

  manifest:
    needs: server-image
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create -t "${{ env.IMAGE }}:main" \
            "${{ env.IMAGE }}:build-linux-amd64" \
            "${{ env.IMAGE }}:build-linux-arm64"
